# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7a301b34198f5bebdc725f06b499cdcc84c4332a88921782ff5b91cd97a1c2cf385e083b8b5cb83b1b3e494f7e6903b1b549c103e224500aaff2ee94c33067

test:
  secret_key_base: db4ffb43bd38fc24e42815ee8f25b4d0ca979dac446b9f8010b71d720cf8ebbc8860e0d4770b6ea75844645ca5ea76a4de741a9c045925891c9ecd82f0d9a903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
